{
 "title": "PanelDashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "dataset": "paneldb",
     "rawSql": "SELECT timestamp, vb FROM paneldb.channelRead "
    }
   ]
  },
  {
   "title": "Channel State",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "paneldb",
     "rawSql": "SELECT ch1 AS \"CH 1\", ch2 AS \"CH 2\", ch3 AS \"CH 3\", ch4 AS \"CH 4\" FROM paneldb.channelRead "
    }
   ]
  },
  { "title": "Channel Switches", "type": "speakyourcode-button-panel", "gridPos": { "h": 3, "w": 9, "x": 12, "y": 5 } },
  {
   "title": "Channel Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "dataset": "paneldb",
     "rawSql": "SELECT timestamp, i1 AS \"Ch1\", i2 AS \"Ch2\", i3 AS \"Ch3\", i4 AS \"Ch4\" FROM paneldb.channelRead "
    }
   ]
  }
 ]
}