{
 "title": "PanelDashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Channel State",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "paneldb",
     "rawSql": "SELECT ch1 AS \"CH 1\", ch2 AS \"CH 2\", ch3 AS \"CH 3\", ch4 AS \"CH 4\" FROM paneldb.channelRead "
    }
   ]
  },
  {
   "title": "Channel Switches",
   "type": "speakyourcode-button-panel",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nanogrid Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "paneldb",
     "rawSql": "SELECT timestamp, psol AS \"Solar\", pbatt AS \"Battery\", pload AS \"Load\" FROM paneldb.channelRead "
    }
   ]
  },
  {
   "title": "Battery % State of Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "paneldb",
     "rawSql": "SELECT timestamp, soc FROM paneldb.channelRead "
    }
   ]
  },
  {
   "title": "Channel Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "dataset": "paneldb",
     "rawSql": "SELECT timestamp, i1 AS \"Ch1\", i2 AS \"Ch2\", i3 AS \"Ch3\", i4 AS \"Ch4\" FROM paneldb.channelRead "
    }
   ]
  },
  {
   "title": "High-Current Measurement",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "paneldb",
     "rawSql": "SELECT ia1 AS \"Solar\", ia7 AS \"Fridge\", timestamp FROM paneldb.channelRead "
    }
   ]
  }
 ]
}